apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-be-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "resource-management-chart.name" . }}
data:
  # Application Configuration
  SERVER_PORT: 8080
  
  # Database Configuration
  DB_URL: {{ .Values.be.dbUrl | quote }}
  
  # Keycloak Configuration  
  KEYCLOAK_AUTH_SERVER_URL: {{ .Values.be.keycloakAuthServerUrl | quote }}
  KEYCLOAK_REALM: {{ .Values.be.keycloakRealm | quote }}
  
  # CORS Configuration
  FRONTEND_APP_URL: "https://{{ .Values.fe.ingress.host }}/"