apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-be
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "resource-management.labels" (dict "context" . "component" "backend") | nindent 4 }}
spec:
  replicas: {{ .Values.be.replicaCount }}
  selector:
    matchLabels:
      {{- include "resource-management.selectorLabels" (dict "context" . "component" "backend") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "resource-management.selectorLabels" (dict "context" . "component" "backend") | nindent 8 }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.be.image.repository }}:{{ .Values.be.image.tag }}"
          ports:
            - containerPort: {{ .Values.be.containerPort }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-be-config
            - secretRef:
                name: {{ .Release.Name }}-be-secret
          resources:
            {{- toYaml .Values.be.resources | nindent 12 }}