apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-be
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "resource-management-chart.name" . }}
spec:
  replicas: {{ .Values.be.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "resource-management-chart.name" . }}
      component: backend
  template:
    metadata:
      labels:
        app: {{ include "resource-management-chart.name" . }}
        component: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.be.image.repository }}:{{ .Values.be.image.tag }}"
          ports:
            - containerPort: {{ .Values.be.containerPort }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-be-config
            - secretRef:
                name: {{ .Release.Name }}-be-secret
          resources:
            {{- toYaml .Values.be.resources | nindent 12 }}