apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-be-ingress
  labels:
    {{- include "resource-management.labels" (dict "context" . "component" "backend") | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.be.ingress.host }}
      http:
        paths:
          - path: {{ .Values.be.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-be-service
                port:
                  number: 8080