apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-be-ingress
  labels:
    {{- include "resource-management.labels" (dict "context" . "component" "backend") | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: nginx-external
  rules:
    - host: {{ .Values.be.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}-be-service
                port:
                  number: {{ .Values.be.containerPort }}
            path: {{ .Values.be.ingress.path }}
            pathType: Prefix
  tls:
    - hosts:
        - {{ .Values.be.ingress.host }}
      secretName: resource-management-be-ingress-tls