apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-be-secret
type: Opaque
data:
  DB_USER: {{ include "resource-management.database.username" . }}
  DB_PASSWORD: {{ include "resource-management.database.password" . }}
  KEYCLOAK_CLIENT_SECRET: {{ .Values.be.secrets.keycloakClientSecret | b64enc | quote }}