apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-be-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "resource-management-chart.name" . }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ include "resource-management-chart.name" . }}
    component: backend