apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-be-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  DB_USER: {{ .Values.be.secrets.dbUser | quote }}
  DB_PASSWORD: {{ .Values.be.secrets.dbPassword | quote }}
  KEYCLOAK_CLIENT_SECRET: {{ .Values.be.secrets.keycloakClientSecret | quote }}
  KEYCLOAK_ADMIN_USER: {{ .Values.be.secrets.keycloakAdminUser | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.be.secrets.keycloakAdminPassword | quote }}