apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-be-service
  labels:
    {{- include "prognose.labels" (dict "context" . "component" "backend") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "prognose.selectorLabels" (dict "context" . "component" "backend") | nindent 4 }}