apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-event-processor
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "resource-management-chart.name" . }}
spec:
  replicas: {{ .Values.eventProcessor.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "resource-management-chart.name" . }}
      component: event-processor
  template:
    metadata:
      labels:
        app: {{ include "resource-management-chart.name" . }}
        component: event-processor
    spec:
      containers:
        - name: event-processor
          image: "{{ .Values.eventProcessor.image.repository }}:{{ .Values.eventProcessor.image.tag }}"
          ports:
            - containerPort: {{ .Values.eventProcessor.containerPort }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-event-processor-config
            - secretRef:
                name: {{ .Release.Name }}-event-processor-secret
          resources:
            {{- toYaml .Values.eventProcessor.resources | nindent 12 }}