apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-event-processor-secret
type: Opaque
data:
  # Database secrets
  DB_USER: {{ include "prognose.database.username" . }}
  DB_PASSWORD: {{ include "prognose.database.password" . }}

  # Keycloak secrets
  KEYCLOAK_CLIENT_SECRET: {{ .Values.eventProcessor.secrets.keycloakClientSecret | b64enc | quote }}