apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-event-processor-config
data:
  # Application Configuration
  SERVER_PORT: {{ .Values.be.containerPort | quote }}
  
  DB_URL: {{ include "prognose.database.url" . }}
  
  # Keycloak Configuration  
  KEYCLOAK_AUTH_SERVER_URL: {{ .Values.be.config.keycloakAuthServerUrl | quote }}
  KEYCLOAK_REALM: {{ .Values.be.config.keycloakRealm | quote }}
  KEYCLOAK_CLIENT_ID: {{ .Values.be.config.keycloakClientId | quote }}