apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-event-processor-config
  namespace: {{ .Values.namespace }}
data:
  # Application Configuration
  SERVER_PORT: {{ .Values.eventProcessor.containerPort }}
  
  DB_URL: {{ include "resource-management.database.url" . }}
  
  # Keycloak Configuration  
  KEYCLOAK_AUTH_SERVER_URL: {{ .Values.be.config.keycloakAuthServerUrl | quote }}
  KEYCLOAK_REALM: {{ .Values.be.config.keycloakRealm | quote }}