apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-fe
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "resource-management-chart.name" . }}
    component: frontend
spec:
  replicas: {{ .Values.fe.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "resource-management-chart.name" . }}
      component: frontend
  template:
    metadata:
      labels:
        app: {{ include "resource-management-chart.name" . }}
        component: frontend
    spec:
      containers:
        - name: fe
          image: "{{ .Values.fe.image.repository }}:{{ .Values.fe.image.tag }}"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-fe-config
          resources:
            {{- toYaml .Values.fe.resources | nindent 12 }}