apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-fe-ingress
  labels:
    {{- include "resource-management.labels" (dict "context" . "component" "frontend") | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: nginx-external
  rules:
    - host: {{ .Values.fe.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}-fe-service
                port:
                  number: 80
            # path: /path
            # pathType: Prefix
  tls:
    - hosts:
        - {{ .Values.fe.ingress.host }}
      secretName: un-qualche-nome-che-verra-creato #TODO: change this to a more meaningful name