apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fe-service
  labels:
    {{- include "prognose.labels" (dict "context" . "component" "frontend") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "prognose.selectorLabels" (dict "context" . "component" "frontend") | nindent 4 }}