{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres-service
  labels:
    {{- include "prognose.labels" (dict "context" . "component" "postgresql") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "prognose.selectorLabels" (dict "context" . "component" "postgresql") | nindent 4 }}
{{- end }}