{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
  labels:
    {{- include "prognose.labels" (dict "context" . "component" "postgresql") | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ include "prognose.database.username" . }}
  POSTGRES_PASSWORD: {{ include "prognose.database.password" . }}
{{- end }}